spring.application.name=FSD-Development
spring.datasource.url=jdbc:postgresql://localhost:5432/flowend
spring.datasource.username=postgres
spring.datasource.password=112233Ver#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# optional: port override
server.port=8082


